name 'demo_project2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures demo_project2'
long_description 'Installs/Configures demo_project2'
version '0.1.0'
