name 'module_1'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures module_1'
long_description 'Installs/Configures module_1'
version '0.1.1'
