name 'module_2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures module_2'
long_description 'Installs/Configures module_2'
version '0.1.0'
